/**
 * Seed Script — populates MongoDB Atlas with plants and glossary data
 * Run with: npm run seed
 */
require('dotenv').config();
const mongoose = require('mongoose');
const Plant = require('../models/Plant');
const Glossary = require('../models/Glossary');

const plants = [
  {
    plantId: 1,
    name: 'Turmeric',
    sci: 'Curcuma longa',
    emoji: '🟡',
    cat: 'Anti-inflammatory',
    tags: ['Inflammation', 'Digestion', 'Immunity'],
    desc: 'Golden spice with powerful curcumin compounds, used for millennia in Ayurvedic medicine to treat inflammation, support digestion, and boost immunity.',
    origin: 'South Asia',
    part: 'Rhizome',
    flavor: 'Warm, bitter, earthy',
    preparation: 'Tea, paste, capsules, golden milk, added to cooking',
    dosage: '400–600mg curcumin extract, 3× daily with black pepper',
    caution: 'High doses may cause GI upset. Avoid with blood thinners or before surgery.',
    rating: 5,
    featured: true,
    symptoms: ['joint pain', 'arthritis', 'inflammation', 'indigestion', 'low immunity'],
    color: '#f5e6c0',
  },
  {
    plantId: 2,
    name: 'Ashwagandha',
    sci: 'Withania somnifera',
    emoji: '🌰',
    cat: 'Adaptogen',
    tags: ['Stress', 'Sleep', 'Vitality'],
    desc: 'Ancient adaptogenic root revered in Ayurveda for over 3000 years. Helps the body manage stress, supports sleep, and restores energy and vitality.',
    origin: 'India, North Africa',
    part: 'Root',
    flavor: 'Bitter, earthy, horse-like',
    preparation: 'Powder in warm milk, capsules, tincture',
    dosage: '300–600mg root extract daily for 8–12 weeks',
    caution: 'Avoid during pregnancy. May interact with thyroid and immunosuppressant medications.',
    rating: 5,
    featured: true,
    symptoms: ['stress', 'anxiety', 'fatigue', 'insomnia', 'low libido'],
    color: '#dff0df',
  },
  {
    plantId: 3,
    name: 'Holy Basil (Tulsi)',
    sci: 'Ocimum tenuiflorum',
    emoji: '🌿',
    cat: 'Adaptogen',
    tags: ['Stress', 'Immunity', 'Respiratory'],
    desc: "Sacred 'Queen of Herbs' in Hinduism with extraordinary healing breadth — adaptogenic, antimicrobial, expectorant, and immunomodulatory.",
    origin: 'India',
    part: 'Leaves, seeds, roots',
    flavor: 'Clove-like, peppery, slightly sweet',
    preparation: 'Fresh tea, juice, tincture, steam inhalation',
    dosage: '300–2000mg leaf powder daily, or 2–3 cups of tea',
    caution: 'May lower blood sugar and thin blood. Use caution before surgery.',
    rating: 4,
    featured: true,
    symptoms: ['stress', 'cold', 'cough', 'fever', 'respiratory infection'],
    color: '#d6f5d8',
  },
  {
    plantId: 4,
    name: 'Ginger',
    sci: 'Zingiber officinale',
    emoji: '🫚',
    cat: 'Digestive',
    tags: ['Nausea', 'Digestion', 'Inflammation'],
    desc: 'Warming rhizome with potent anti-nausea and anti-inflammatory effects, backed by the most clinical trials of any medicinal herb.',
    origin: 'Southeast Asia',
    part: 'Rhizome',
    flavor: 'Spicy, warm, citrusy',
    preparation: 'Fresh ginger tea, capsules, grated into food, juice',
    dosage: '1–3g dried ginger daily; 250mg extract 4× daily for nausea',
    caution: 'High doses may increase bleeding risk. Avoid 2 weeks before surgery.',
    rating: 5,
    featured: true,
    symptoms: ['nausea', 'morning sickness', 'motion sickness', 'indigestion', 'inflammation', 'cold'],
    color: '#fde8c8',
  },
  {
    plantId: 5,
    name: 'Neem',
    sci: 'Azadirachta indica',
    emoji: '🌳',
    cat: 'Antimicrobial',
    tags: ['Skin', 'Oral Health', 'Antimicrobial'],
    desc: "Village pharmacy in a tree. Over 130 biologically active compounds make neem one of the most versatile medicinal plants — dubbed 'the wonder tree'.",
    origin: 'India, South Asia',
    part: 'Leaves, bark, seeds, oil',
    flavor: 'Intensely bitter',
    preparation: 'Leaf powder, neem oil (topical), twig for teeth, decoction',
    dosage: '500mg leaf extract 1–2× daily; topical oil diluted 1:10',
    caution: 'Do NOT give to children internally. Toxic in high doses. Avoid in pregnancy.',
    rating: 4,
    featured: false,
    symptoms: ['acne', 'skin infections', 'dandruff', 'dental plaque', 'blood sugar', 'intestinal worms'],
    color: '#c8e8c0',
  },
  {
    plantId: 6,
    name: 'Brahmi',
    sci: 'Bacopa monnieri',
    emoji: '🧠',
    cat: 'Nootropic',
    tags: ['Memory', 'Brain', 'Anxiety'],
    desc: 'Ayurvedic brain tonic that enhances memory consolidation, reduces anxiety, and provides neuroprotective effects through bacosides.',
    origin: 'India, wetlands',
    part: 'Whole plant',
    flavor: 'Bitter, astringent',
    preparation: 'Powder in warm ghee or milk, capsules, fresh juice',
    dosage: '300mg standardized extract (45% bacosides) daily',
    caution: 'May slow heart rate. Avoid with sedatives. Take with food to reduce nausea.',
    rating: 4,
    featured: false,
    symptoms: ['poor memory', 'brain fog', 'anxiety', 'adhd', 'cognitive decline'],
    color: '#d0eef8',
  },
  {
    plantId: 7,
    name: 'Shatavari',
    sci: 'Asparagus racemosus',
    emoji: '🌸',
    cat: 'Adaptogen',
    tags: ["Women's Health", 'Fertility', 'Hormones'],
    desc: "Premier Ayurvedic tonic for female reproductive health, supporting hormonal balance, fertility, lactation, and menopausal transitions.",
    origin: 'India, Himalayas',
    part: 'Root tubers',
    flavor: 'Sweet, bitter, slightly cooling',
    preparation: 'Powder in warm milk with ghee, capsules, decoction',
    dosage: '3–6g root powder daily in milk',
    caution: 'Avoid with hormone-sensitive conditions. May cause bloating initially.',
    rating: 4,
    featured: false,
    symptoms: ['menstrual issues', 'menopause', 'low milk production', 'hormonal imbalance', 'fertility'],
    color: '#f5d6e8',
  },
  {
    plantId: 8,
    name: 'Moringa',
    sci: 'Moringa oleifera',
    emoji: '🌱',
    cat: 'Superfood',
    tags: ['Nutrition', 'Energy', 'Inflammation'],
    desc: "'Miracle tree' providing 92 nutrients, 46 antioxidants, and all 9 essential amino acids. One of the most nutrient-dense plants on earth.",
    origin: 'Sub-Himalayan India',
    part: 'Leaves, pods, seeds, bark',
    flavor: 'Slightly bitter, grassy, earthy',
    preparation: 'Leaf powder in smoothies or tea, fresh leaves in cooking',
    dosage: '2–6g leaf powder daily',
    caution: 'Avoid seeds and root bark during pregnancy. May lower blood pressure.',
    rating: 5,
    featured: false,
    symptoms: ['fatigue', 'malnutrition', 'inflammation', 'high blood sugar', 'anemia'],
    color: '#c0e8c0',
  },
  {
    plantId: 9,
    name: 'Amla',
    sci: 'Phyllanthus emblica',
    emoji: '🫐',
    cat: 'Superfood',
    tags: ['Immunity', 'Hair', 'Antioxidant'],
    desc: 'Indian Gooseberry — highest natural source of Vitamin C. A cornerstone of Ayurvedic medicine for longevity, hair health, and immunity.',
    origin: 'India, Southeast Asia',
    part: 'Fruit',
    flavor: 'Sour, astringent, then sweet',
    preparation: 'Fresh fruit, dried, powder, juice, hair oil, jam (murabba)',
    dosage: '500mg–1g standardized extract daily, or 1–2 fresh fruits',
    caution: 'May lower blood sugar and thin blood. Avoid before surgery.',
    rating: 5,
    featured: false,
    symptoms: ['hair loss', 'low immunity', 'high cholesterol', 'acidity', 'premature aging'],
    color: '#d0f0c0',
  },
  {
    plantId: 10,
    name: 'Giloy',
    sci: 'Tinospora cordifolia',
    emoji: '🔵',
    cat: 'Immunity',
    tags: ['Immunity', 'Fever', 'Detox'],
    desc: "'Amrita' (divine nectar) — a rejuvenating climber that modulates immunity, fights fever, and detoxifies the body at a deep level.",
    origin: 'India, tropical Asia',
    part: 'Stem, roots',
    flavor: 'Bitter, astringent',
    preparation: 'Fresh stem juice, decoction, powder, capsules',
    dosage: '300–400mg stem extract daily',
    caution: 'May lower blood sugar. Use caution with autoimmune conditions. Avoid in pregnancy.',
    rating: 5,
    featured: false,
    symptoms: ['fever', 'dengue', 'low immunity', 'chronic fatigue', 'arthritis', 'gout'],
    color: '#c8d8f0',
  },
  {
    plantId: 11,
    name: 'Valerian',
    sci: 'Valeriana officinalis',
    emoji: '😴',
    cat: 'Nervine',
    tags: ['Sleep', 'Anxiety', 'Muscle Spasm'],
    desc: 'European sleep herb that raises GABA levels in the brain to calm the nervous system and significantly improve sleep quality and latency.',
    origin: 'Europe, parts of Asia',
    part: 'Root',
    flavor: 'Earthy, musky, pungent',
    preparation: 'Capsules (preferred), tincture, tea (unpleasant taste)',
    dosage: '300–600mg standardized extract 30–60 minutes before bed',
    caution: 'Do not combine with sedatives or alcohol. Avoid long-term continuous use.',
    rating: 4,
    featured: false,
    symptoms: ['insomnia', 'anxiety', 'restlessness', 'muscle tension', 'night sweats'],
    color: '#e8d8f8',
  },
  {
    plantId: 12,
    name: 'Chamomile',
    sci: 'Matricaria chamomilla',
    emoji: '🌼',
    cat: 'Nervine',
    tags: ['Sleep', 'Digestion', 'Skin'],
    desc: 'Gentle calming herb suitable for all ages. Apigenin binds to brain receptors to induce relaxation; also soothes GI spasm and skin inflammation.',
    origin: 'Europe, Western Asia',
    part: 'Flowers',
    flavor: 'Apple-like, floral, mildly bitter',
    preparation: 'Tea (9–15g flowers), compress, tincture, topical cream',
    dosage: '2–3 cups of tea daily; 400mg extract for anxiety',
    caution: 'Allergic reactions possible in ragweed-sensitive people. Mild blood thinner.',
    rating: 5,
    featured: false,
    symptoms: ['insomnia', 'anxiety', 'upset stomach', 'skin irritation', 'menstrual cramps'],
    color: '#fef5c8',
  },
  {
    plantId: 13,
    name: 'Peppermint',
    sci: 'Mentha × piperita',
    emoji: '🌬️',
    cat: 'Digestive',
    tags: ['IBS', 'Headache', 'Nausea'],
    desc: 'Cooling herb with menthol proven effective for IBS, tension headaches, nausea, and respiratory congestion in multiple clinical trials.',
    origin: 'Europe, Middle East',
    part: 'Leaves',
    flavor: 'Cool, menthol, intensely minty',
    preparation: 'Tea, enteric-coated capsules for IBS, topical oil for headaches',
    dosage: '0.2–0.4ml enteric-coated oil 3× daily; 1–2 cups tea for general use',
    caution: 'Avoid pure essential oil internally in children. May worsen GERD in some people.',
    rating: 5,
    featured: false,
    symptoms: ['ibs', 'bloating', 'headache', 'nausea', 'congestion', 'bad breath'],
    color: '#c8f0e0',
  },
  {
    plantId: 14,
    name: 'Echinacea',
    sci: 'Echinacea purpurea',
    emoji: '💜',
    cat: 'Immunity',
    tags: ['Cold', 'Flu', 'Immunity'],
    desc: 'Native American herb clinically proven to reduce cold duration by 1.4 days and severity of upper respiratory infections.',
    origin: 'North America',
    part: 'Root and aerial parts',
    flavor: 'Slightly sweet, earthy, tingling on tongue',
    preparation: 'Tea, tincture, capsules, fresh pressed juice',
    dosage: '300–500mg extract 3× daily; use for max 10 consecutive days',
    caution: 'Not for continuous use over 10 days. Avoid with autoimmune conditions or immunosuppressants.',
    rating: 4,
    featured: false,
    symptoms: ['cold', 'flu', 'upper respiratory infection', 'low immunity'],
    color: '#f0d8f0',
  },
  {
    plantId: 15,
    name: 'Garlic',
    sci: 'Allium sativum',
    emoji: '🧄',
    cat: 'Antimicrobial',
    tags: ['Cardiovascular', 'Immunity', 'Antimicrobial'],
    desc: 'Allicin-rich bulb with substantial clinical evidence for reducing LDL cholesterol, blood pressure, and risk of cardiovascular events.',
    origin: 'Central Asia',
    part: 'Bulb (cloves)',
    flavor: 'Pungent, spicy, sulfurous',
    preparation: 'Raw (most potent), aged garlic extract, capsules, cooking',
    dosage: '600–1200mg aged extract daily; 2–4 raw cloves daily',
    caution: 'May increase bleeding risk. Space 2+ hours from medications.',
    rating: 5,
    featured: false,
    symptoms: ['high cholesterol', 'high blood pressure', 'cold', 'infection', 'atherosclerosis'],
    color: '#f0f0e0',
  },
];

const glossary = [
  { term: 'Adaptogen', def: 'Herbs that increase non-specific resistance to physical, chemical, or biological stressors, helping the body restore normal physiological function.' },
  { term: 'Decoction', def: 'A concentrated liquid prepared by simmering tough plant material (roots, bark, seeds, stems) in water for an extended period, usually 20–30 minutes.' },
  { term: 'Tincture', def: 'A potent extract of plant material prepared in alcohol (or glycerin as an alternative), typically in 1:5 or 1:10 herb-to-solvent ratios.' },
  { term: 'Nervine', def: 'Herbs that specifically nourish, strengthen, and support the nervous system — either calming (sedative nervines) or stimulating depending on the plant.' },
  { term: 'Nootropic', def: 'Substances that enhance cognitive function including memory, creativity, focus, and executive function without significant side effects.' },
  { term: 'Carminative', def: 'Herbs that relieve digestive discomfort by promoting the expulsion of gas and relaxing intestinal spasms.' },
  { term: 'Astringent', def: 'A quality that causes contraction of body tissues; plants with this property tighten mucous membranes, reduce secretions, and help stop bleeding.' },
  { term: 'Expectorant', def: 'Herbs that thin and loosen mucus in the respiratory tract, making it easier to cough up and expel.' },
  { term: 'Adaptogenic Tonic', def: 'An herbal preparation that improves overall resilience and restores systemic balance without targeting a specific organ or disease state.' },
  { term: 'Bioavailability', def: 'The proportion of an active compound that enters systemic circulation and exerts its biological effect after introduction into the body.' },
  { term: 'Phytochemical', def: 'Biologically active chemical compounds naturally produced by plants, including alkaloids, flavonoids, terpenes, phenols, and polyphenols.' },
  { term: 'Rasayana', def: 'Ayurvedic category of rejuvenating substances used to promote longevity, enhance memory, boost immunity, and restore vitality after illness.' },
  { term: 'Kshirpak', def: 'Ayurvedic milk decoction where herbs are simmered in milk until water evaporates; used for heart, bone, and rejuvenating preparations.' },
  { term: 'Bitter Tonic', def: 'Herbs with bitter compounds (iridoids, alkaloids) that stimulate digestive secretions, bile flow, and improve nutrient absorption.' },
  { term: 'Diuretic', def: 'Herbs that increase kidney filtration and urine output, helping eliminate excess fluid, salts, and metabolic waste from the body.' },
];

const seed = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('✅ Connected to MongoDB Atlas');

    // Clear existing data
    await Plant.deleteMany({});
    await Glossary.deleteMany({});
    console.log('🗑️  Cleared existing plants and glossary data');

    // Insert fresh data
    await Plant.insertMany(plants);
    console.log(`🌿 Seeded ${plants.length} plants`);

    await Glossary.insertMany(glossary);
    console.log(`📖 Seeded ${glossary.length} glossary terms`);

    console.log('\n✅ Database seeded successfully!');
    process.exit(0);
  } catch (error) {
    console.error('❌ Seed failed:', error.message);
    process.exit(1);
  }
};

seed();
